services:
  ms-discovery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-discovery

    restart: always

    ports:
      - "8761:8761"

    environment:
      - SERVER_PORT=8761
      - SPRING_PROFILES_ACTIVE=${PROFILE_SPRING}
    # Configuraci√≥n de red
    networks:
      - siim-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

# Definimos la red
networks:
  siim-network:
    name: siim-global-net
    external: true